package com.edutrack.service;

import com.edutrack.dto.AuthResponse;
import com.edutrack.dto.LoginRequest;
import com.edutrack.dto.RegisterRequest;

public interface AuthService {

    AuthResponse register(RegisterRequest registerRequest);

    AuthResponse login(LoginRequest loginRequest);
}
